# Generated by Django 5.2.4 on 2025-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_answer_choice_alter_answer_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="openai_batches", to="main.question"
                    ),
                ),
            ],
        ),
    ]
