# Generated by Django 5.2.4 on 2025-07-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_openaibatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaibatch',
            name='questions',
        ),
        migrations.AddField(
            model_name='openaibatch',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='openai_batches', to='main.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openaibatch',
            name='status',
            field=models.CharField(db_index=True, default='*', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openaibatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='openaibatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
