# Generated by Django 5.2.4 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_openaibatch_questions_openaibatch_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaibatch',
            name='errors',
            field=models.JSONField(default=dict),
        ),
    ]
