# Generated by Django 5.2.4 on 2025-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_openaibatch_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaibatch',
            name='errors',
            field=models.TextField(blank=True),
        ),
    ]
