# Generated by Django 5.2.4 on 2025-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_openaibatch_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaibatch',
            name='output_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
