# Generated by Django 5.2.4 on 2025-07-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_openaibatch_output_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaibatch',
            name='error_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
