# Generated by Django 5.2.4 on 2025-07-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_openaibatch_error_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
