# Generated by Django 5.2.4 on 2025-07-09 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_openaibatch_data_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="run_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="openaibatch",
            name="run_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
