# Generated by Django 5.2.4 on 2025-07-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_answer_run_id_openaibatch_run_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaibatch',
            options={'verbose_name_plural': 'OpenAI Batches'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='template',
            new_name='text',
        ),
    ]
