# Generated by Django 5.2.4 on 2025-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_openaibatch_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "queued"),
                    ("running", "running"),
                    ("importing", "importing"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
