# Generated by Django 5.2.4 on 2025-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_question_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("queued", "queued"),
                    ("running", "running"),
                    ("importing", "importing"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
