# Generated by Django 5.2.4 on 2025-07-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_question_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="user",
            new_name="created_by",
        ),
    ]
